#ifndef CMG_WASM_H_GENERATED_
#define CMG_WASM_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: 'env' 'e' */
extern u32 (*Z_envZ_eZ_iv)(void);
/* import: 'env' 'f' */
extern void (*Z_envZ_fZ_vi)(u32);
/* import: 'env' 'g' */
extern u32 (*Z_envZ_gZ_iii)(u32, u32);
/* import: 'env' 'h' */
extern void (*Z_envZ_hZ_viiiii)(u32, u32, u32, u32, u32);
/* import: 'env' 'i' */
extern f64 (*Z_envZ_iZ_dv)(void);
/* import: 'env' 'j' */
extern void (*Z_envZ_jZ_vv)(void);
/* import: 'env' 'k' */
extern void (*Z_envZ_kZ_vii)(u32, u32);
/* import: 'env' 'l' */
extern void (*Z_envZ_lZ_vi)(u32);
/* import: 'env' 'm' */
extern u32 (*Z_envZ_mZ_iiiiii)(u32, u32, u32, u32, u32);
/* import: 'env' 'n' */
extern u32 (*Z_envZ_nZ_iiiii)(u32, u32, u32, u32);
/* import: 'env' 'o' */
extern u32 (*Z_envZ_oZ_ii)(u32);
/* import: 'env' 'p' */
extern u32 (*Z_envZ_pZ_iiii)(u32, u32, u32);
/* import: 'env' 'q' */
extern void (*Z_envZ_qZ_vv)(void);
/* import: 'env' 'r' */
extern void (*Z_envZ_rZ_vi)(u32);
/* import: 'env' 's' */
extern u32 (*Z_envZ_sZ_ii)(u32);
/* import: 'env' 't' */
extern u32 (*Z_envZ_tZ_iiii)(u32, u32, u32);
/* import: 'env' 'u' */
extern void (*Z_envZ_uZ_vii)(u32, u32);
/* import: 'env' 'v' */
extern u32 (*Z_envZ_vZ_iv)(void);
/* import: 'env' 'w' */
extern u32 (*Z_envZ_wZ_iv)(void);
/* import: 'env' 'x' */
extern u32 (*Z_envZ_xZ_iiii)(u32, u32, u32);
/* import: 'env' 'y' */
extern u32 (*Z_envZ_yZ_iiidiiii)(u32, u32, f64, u32, u32, u32, u32);
/* import: 'env' 'z' */
extern u32 (*Z_envZ_zZ_iii)(u32, u32);
/* import: 'env' 'A' */
extern void (*Z_envZ_AZ_vv)(void);
/* import: 'env' 'B' */
extern u32 (*Z_envZ_BZ_iii)(u32, u32);
/* import: 'env' 'C' */
extern void (*Z_envZ_CZ_vi)(u32);
/* import: 'env' 'D' */
extern u32 (*Z_envZ_DZ_iii)(u32, u32);
/* import: 'env' 'E' */
extern u32 (*Z_envZ_EZ_ii)(u32);
/* import: 'env' 'F' */
extern void (*Z_envZ_FZ_vi)(u32);
/* import: 'env' 'G' */
extern f64 (*Z_envZ_GZ_diii)(u32, u32, u32);
/* import: 'env' 'H' */
extern void (*Z_envZ_HZ_vi)(u32);
/* import: 'env' 'I' */
extern u32 (*Z_envZ_IZ_iii)(u32, u32);
/* import: 'env' 'J' */
extern void (*Z_envZ_JZ_vii)(u32, u32);
/* import: 'env' 'K' */
extern void (*Z_envZ_KZ_viii)(u32, u32, u32);
/* import: 'env' 'L' */
extern void (*Z_envZ_LZ_vii)(u32, u32);
/* import: 'env' 'M' */
extern void (*Z_envZ_MZ_viii)(u32, u32, u32);
/* import: 'env' 'N' */
extern void (*Z_envZ_NZ_viiiii)(u32, u32, u32, u32, u32);
/* import: 'env' 'O' */
extern void (*Z_envZ_OZ_viii)(u32, u32, u32);
/* import: 'env' 'P' */
extern void (*Z_envZ_PZ_vii)(u32, u32);
/* import: 'env' 'Q' */
extern void (*Z_envZ_QZ_viiiii)(u32, u32, u32, u32, u32);
/* import: 'env' 'R' */
extern u32 (*Z_envZ_RZ_iii)(u32, u32);
/* import: 'env' 'S' */
extern u32 (*Z_envZ_SZ_iii)(u32, u32);
/* import: 'env' 'T' */
extern u32 (*Z_envZ_TZ_iii)(u32, u32);
/* import: 'env' 'U' */
extern void (*Z_envZ_UZ_vi)(u32);
/* import: 'env' 'V' */
extern u32 (*Z_envZ_VZ_iv)(void);
/* import: 'env' 'W' */
extern u32 (*Z_envZ_WZ_ii)(u32);
/* import: 'env' 'X' */
extern void (*Z_envZ_XZ_viiiiiii)(u32, u32, u32, u32, u32, u32, u32);
/* import: 'env' 'Y' */
extern void (*Z_envZ_YZ_viiiiii)(u32, u32, u32, u32, u32, u32);
/* import: 'env' 'Z' */
extern void (*Z_envZ_Z5AZ_viiiii)(u32, u32, u32, u32, u32);
/* import: 'env' '_' */
extern void (*Z_envZ__Z_viiii)(u32, u32, u32, u32);
/* import: 'env' '$' */
extern void (*Z_envZ_Z24Z_viii)(u32, u32, u32);
/* import: 'env' 'aa' */
extern void (*Z_envZ_aaZ_vi)(u32);
/* import: 'env' '__table_base' */
extern u32 (*Z_envZ___table_baseZ_i);
/* import: 'env' 'a' */
extern u32 (*Z_envZ_aZ_i);
/* import: 'env' 'b' */
extern u32 (*Z_envZ_bZ_i);
/* import: 'env' 'c' */
extern u32 (*Z_envZ_cZ_i);
/* import: 'env' 'd' */
extern u32 (*Z_envZ_dZ_i);
/* import: 'env' 'memory' */
extern wasm_rt_memory_t (*Z_envZ_memory);
/* import: 'env' 'table' */
extern wasm_rt_table_t (*Z_envZ_table);

/* export: 'ba' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_baZ_ii))(u32);
/* export: 'ca' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_caZ_ii))(u32);
/* export: 'da' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_daZ_ii))(u32);
/* export: 'ea' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_eaZ_iiiii))(u32, u32, u32, u32);
/* export: 'fa' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_faZ_iiiii))(u32, u32, u32, u32);
/* export: 'ga' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_gaZ_iiiii))(u32, u32, u32, u32);
/* export: 'ha' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_haZ_iiiii))(u32, u32, u32, u32);
/* export: 'ia' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_iaZ_iiiii))(u32, u32, u32, u32);
/* export: 'ja' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_jaZ_iiiii))(u32, u32, u32, u32);
/* export: 'ka' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_kaZ_iiiii))(u32, u32, u32, u32);
/* export: 'la' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_laZ_iiiii))(u32, u32, u32, u32);
/* export: 'ma' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_maZ_iiiii))(u32, u32, u32, u32);
/* export: 'na' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_naZ_iiiii))(u32, u32, u32, u32);
/* export: 'oa' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_oaZ_iiiii))(u32, u32, u32, u32);
/* export: 'pa' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_paZ_iiiii))(u32, u32, u32, u32);
/* export: 'qa' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_qaZ_iiiii))(u32, u32, u32, u32);
/* export: 'ra' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_raZ_iiiii))(u32, u32, u32, u32);
/* export: 'sa' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_saZ_iiiii))(u32, u32, u32, u32);
/* export: 'ta' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_taZ_iiiii))(u32, u32, u32, u32);
/* export: 'ua' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_uaZ_iiiii))(u32, u32, u32, u32);
/* export: 'va' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_vaZ_iiiii))(u32, u32, u32, u32);
/* export: 'wa' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_waZ_iv))(void);
/* export: 'xa' */
extern void (*WASM_RT_ADD_PREFIX(Z_xaZ_vv))(void);
/* export: 'ya' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_yaZ_iv))(void);
/* export: 'za' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_zaZ_ii))(u32);
/* export: 'Aa' */
extern void (*WASM_RT_ADD_PREFIX(Z_AaZ_vi))(u32);
/* export: 'Ba' */
extern void (*WASM_RT_ADD_PREFIX(Z_BaZ_vi))(u32);
/* export: 'Ca' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_CaZ_ii))(u32);
/* export: 'Da' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_DaZ_iii))(u32, u32);
/* export: 'Ea' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_EaZ_ii))(u32);
/* export: 'Fa' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_FaZ_ii))(u32);
/* export: 'Ga' */
extern void (*WASM_RT_ADD_PREFIX(Z_GaZ_vi))(u32);
/* export: 'Ha' */
extern void (*WASM_RT_ADD_PREFIX(Z_HaZ_vii))(u32, u32);
/* export: 'Ia' */
extern void (*WASM_RT_ADD_PREFIX(Z_IaZ_viii))(u32, u32, u32);
/* export: 'Ja' */
extern void (*WASM_RT_ADD_PREFIX(Z_JaZ_vi))(u32);
/* export: 'Ka' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_KaZ_iv))(void);
/* export: 'La' */
extern void (*WASM_RT_ADD_PREFIX(Z_LaZ_vv))(void);
/* export: 'Ma' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_MaZ_ii))(u32);
u32 cmg_debug_get_g6(void);
u32 cmg_debug_get_g7(void);
u32 cmg_debug_get_g9(void);
void cmg_debug_set_g7(u32 value);
#ifdef __cplusplus
}
#endif

#endif  /* CMG_WASM_H_GENERATED_ */
