/**
 * The single crossing between Bilibili page time and a receiver's presentation
 * clock, scoped to ONE media generation.
 *
 * Precisely what is immutable: the TIME MAPPING. Once built, `offsetSeconds`
 * never changes and the two conversion methods are pure functions of it.
 *
 * What is not: the set of media identities the adapter accepts. Those are
 * MONOTONIC — added, never removed — and every addition must be backed by
 * evidence that the media belongs to this generation:
 *
 *   1. the content id the generation itself declared (the bridge's URI for this
 *      load) is bound at construction, because the sender chose it and needs no
 *      receiver evidence for it;
 *   2. a media session id is added only for a media that STATES a content id
 *      agreeing with that declaration (see the sender's
 *      `confirmReceiverMediaIdentity`).
 *
 * That two-stage rule exists because the timeline and the media are not known at
 * the same instant: a bridge reply states the timeline, while the receiver
 * creates a media object per `mediaSessionId` — and the LOAD callback can hand
 * back the PREVIOUS session's object. A future change that let an arbitrary
 * report, or the LOAD callback's argument, teach the adapter an identity would
 * defeat the check that stops a stale shift from being applied, so binding is
 * deliberately separate from construction rather than a general `setIdentity`
 * API.
 *
 * ## The two clocks
 *
 * A Bilibili DASH cast runs the receiver against a playlist the bridge
 * generated by remuxing from a seek target. That playlist may carry a pad
 * runway in front of the real segments (Chromecast startup compatibility), so:
 *
 *     receiverTime = pageTime + offset
 *
 * `offset` is 0 for every cast whose playlist is padded to the seek target by
 * construction (every Roku cast, every mid-video restart) and 32s for an
 * opening cast that walks its runway.
 *
 * ## Why an adapter and not a number
 *
 * The offset describes ONE generated playlist. Stored as a plain value that any
 * module can update, it becomes a shared mutable guess: a status from the
 * PREVIOUS media converted with the CURRENT offset moves the page by a whole
 * runway, and the wrong page position then looks like a seek request, which
 * restarts the remux, which produces another offset. That loop is what the
 * refactor removes.
 *
 * So the mapping is a value object:
 *
 *   - one adapter per media generation;
 *   - created once from that generation's own bridge reply;
 *   - never mutated afterwards;
 *   - bound to the media identities that generation reports, so a report from a
 *     different media is refused instead of converted with the wrong offset.
 *
 * A module that holds a stale adapter can therefore only produce a correct
 * answer for the old media, or no answer at all. There is no third outcome, and
 * no fallback branch that could invent one.
 */

/**
 * The bridge's statement of a generated playlist's timeline, taken verbatim
 * from `mediaCast:mediaServerStarted`.
 *
 * `receiverStart` and `pageStart` are positions on the two clocks for the same
 * instant of content, so `offset = receiverStart - pageStart`. Neither value is
 * a business position: they exist to define the mapping and to be logged.
 */
export interface DashPresentationIdentity {
    /** The bridge request (media generation) this adapter describes. */
    generationId: string;
    /** Page seconds the remux was generated from (the seek target). */
    pageStart: number;
    /** Receiver seconds the playlist's real content begins at. */
    receiverStart: number;
}

export interface DashPresentation {
    readonly generationId: string;
    /** receiverTime = pageTime + offset. Fixed for this adapter's lifetime. */
    readonly offsetSeconds: number;
    /** True when the identity came from a bridge that stated a presentation. */
    readonly established: boolean;

    pageToReceiver(pageSeconds: number): number;
    receiverToPage(receiverSeconds: number): number;

    /**
     * Can this adapter describe the media a report is about?
     *
     * Media identity, not device identity: a device-level match is what let a
     * stale 32s offset apply to the next media. `contentId` is compared with its
     * cache-busting query stripped (the sender appends a fresh `?v=` per remux
     * restart, so the raw value would refuse its own media), and the media
     * session id is accepted as the alternative identity for reports that echo
     * an id but no contentId.
     */
    describes(media: { contentId?: string; mediaSessionId?: number }): boolean;

    /** The identities this adapter accepts, for diagnostics and tests. */
    describeBindings(): {
        contentIds: string[];
        mediaSessionIds: number[];
    };
}

/** Normalize the identities a report may carry so they can be compared. */
export function normalizeContentId(contentId: unknown): string | undefined {
    if (typeof contentId !== "string" || !contentId) return undefined;
    const queryIndex = contentId.indexOf("?");
    return queryIndex < 0 ? contentId : contentId.slice(0, queryIndex);
}

/**
 * An adapter for a media with NO offset: page time and receiver time are the
 * same clock. Used for Roku DASH capture (where the bridge composes page time
 * into the session itself), CCTV's synthetic DVR and ordinary VOD, and as the
 * safe answer when a bridge never stated a presentation position.
 *
 * It is deliberately a real adapter rather than `undefined`, so every consumer
 * has exactly one code path and no "unknown offset" branch to get wrong.
 */
export function identityPresentation(generationId: string): DashPresentation {
    return createDashPresentation({
        generationId,
        pageStart: 0,
        receiverStart: 0,
        established: false
    });
}

export function createDashPresentation(identity: {
    generationId: string;
    pageStart: number;
    receiverStart: number;
    /** false when the bridge did not state a presentation position. */
    established?: boolean;
    /** Extra media identities (base contentIds) this generation serves. */
    contentIds?: Array<string | undefined>;
}): DashPresentation {
    const pageStart = Number(identity.pageStart);
    const receiverStart = Number(identity.receiverStart);
    const usable =
        Number.isFinite(pageStart) &&
        Number.isFinite(receiverStart) &&
        identity.established !== false &&
        receiverStart >= 0;
    // A pad runway is the only source of a non-zero shift, and the bridge never
    // pads backwards: a negative offset would mean the two values were read from
    // different loads, so it is refused rather than accepted as a guess.
    const offsetSeconds =
        usable && receiverStart >= pageStart ? receiverStart - pageStart : 0;

    const contentIds = new Set<string>();
    for (const raw of identity.contentIds ?? []) {
        const normalized = normalizeContentId(raw);
        if (normalized) contentIds.add(normalized);
    }
    const mediaSessionIds = new Set<number>();

    return {
        generationId: identity.generationId,
        offsetSeconds,
        established: usable,
        pageToReceiver(pageSeconds: number): number {
            const page = Number(pageSeconds);
            if (!Number.isFinite(page)) return page;
            return page + offsetSeconds;
        },
        receiverToPage(receiverSeconds: number): number {
            const receiver = Number(receiverSeconds);
            if (!Number.isFinite(receiver)) return receiver;
            // A receiver position inside the pad runway (or the transient reset
            // right after a reload) maps to before the media's start. The page
            // never had a negative time, so clamp.
            return Math.max(0, receiver - offsetSeconds);
        },
        describes(media: { contentId?: string; mediaSessionId?: number }) {
            const contentId = normalizeContentId(media?.contentId);
            if (contentId && contentIds.has(contentId)) return true;
            return (
                typeof media?.mediaSessionId === "number" &&
                mediaSessionIds.has(media.mediaSessionId)
            );
        },
        describeBindings() {
            return {
                contentIds: [...contentIds],
                mediaSessionIds: [...mediaSessionIds]
            };
        },
        /**
         * Record that this generation also reports under these identities.
         *
         * Monotonic: identities are added, never removed, so an adapter can only
         * grow to describe media it has been shown evidence for.
         *
         * The CALLER owns that evidence. Adding an identity from an arbitrary
         * report, or from the LOAD callback's own Media argument (which can be the
         * previous session), would let the adapter accept foreign media and the
         * whole point of the identity check would be lost — see the two-stage rule
         * in this module's header and the sender's confirmReceiverMediaIdentity.
         */
        bind(media: { contentId?: string; mediaSessionId?: number }) {
            const contentId = normalizeContentId(media?.contentId);
            if (contentId) contentIds.add(contentId);
            if (typeof media?.mediaSessionId === "number") {
                mediaSessionIds.add(media.mediaSessionId);
            }
        }
    } as DashPresentation & {
        bind(media: { contentId?: string; mediaSessionId?: number }): void;
    };
}

/**
 * Teach an adapter which media identities it describes.
 *
 * Called with the media the LOAD itself reports, which is the generation's own
 * media by definition. Separate from `createDashPresentation` because the media
 * object does not exist until after the bridge reply.
 */
export function bindPresentationMedia(
    presentation: DashPresentation,
    media: { contentId?: string; mediaSessionId?: number } | undefined
): void {
    if (!media) return;
    (
        presentation as DashPresentation & {
            bind?: (media: {
                contentId?: string;
                mediaSessionId?: number;
            }) => void;
        }
    ).bind?.(media);
}

/**
 * The offset a media's own customData states, when it states one.
 *
 * `undefined` means the media says nothing (a report that dropped customData, or
 * media that is not a DASH remux). An explicit 0 is NOT undefined: it means this
 * media was loaded without a pad runway, so no offset may be applied to it even
 * if something else carries a stale one.
 */
export function declaredPresentationOffset(
    customData: unknown
): number | undefined {
    if (!customData || typeof customData !== "object") return undefined;
    const raw = (customData as { presentationOffsetSeconds?: unknown })
        .presentationOffsetSeconds;
    if (raw === undefined || raw === null) return undefined;
    const offset = Number(raw);
    return Number.isFinite(offset) ? offset : undefined;
}
